FROM ggoitea/laravel-prod:13-php8.5

WORKDIR /var/www/html

COPY ./docker/php/php.ini-production /usr/local/etc/php/php.ini
COPY ./docker/nginx/nginx.conf-prod /etc/nginx/nginx.conf
RUN mkdir -p /tmp/nginx/client_body \
    && chown -R www-data:www-data /tmp/nginx \
    && chmod 700 /tmp/nginx

COPY . .

RUN mkdir -p storage/logs bootstrap/cache \
    && chown -R www-data:www-data storage bootstrap/cache

