FROM ggoitea/laravel-dev:13-php8.5

WORKDIR /var/www/html

ARG UID=1000
ARG GID=1000

COPY ./docker/php/php.ini-development /usr/local/etc/php/php.ini

RUN addgroup -g ${GID} app \
    && adduser -D -u ${UID} -G app app

USER app
